Devcotainer definition for .Net and Java

diff --git a/.devcontainer/Containerfile b/.devcontainer/Containerfile
--- a/.devcontainer/Containerfile
+++ b/.devcontainer/Containerfile
@@ -1,14 +1,115 @@
-# [Choice] .NET version: 6.0, 3.1, 6.0-bullseye, 3.1-bullseye, 6.0-focal, 3.1-focal
-ARG VARIANT=6.0-focal
-FROM mcr.microsoft.com/vscode/devcontainers/dotnet:0-${VARIANT}
+FROM docker.io/amd64/debian:bullseye-slim
 
-# [Choice] Node.js version: none, lts/*, 18, 16, 14
-ARG NODE_VERSION="none"
-RUN if [ "${NODE_VERSION}" != "none" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi
+RUN apt-get update \
+    && apt-get install -y --no-install-recommends \
+        ca-certificates \
+        \
+        # .NET Core dependencies
+        libc6 \
+        libgcc1 \
+        libgssapi-krb5-2 \
+        libicu67 \
+        libssl1.1 \
+        libstdc++6 \
+        zlib1g \
+        # .NET SDK dependencies
+        curl \
+        git \
+        wget \
+    && rm -rf /var/lib/apt/lists/*
 
-# [Optional] Uncomment this section to install additional OS packages.
-# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
-#     && apt-get -y install --no-install-recommends <your-package-list-here>
+# Dotnet Environment variables
+ENV \
+    # Enable detection of running in a container
+    DOTNET_RUNNING_IN_CONTAINER=true \
+    # Do not generate certificate
+    DOTNET_GENERATE_ASPNET_CERTIFICATE=false \
+    # Do not show first run text
+    DOTNET_NOLOGO=true \
+    # .NET Runtime version
+    DOTNET_VERSION=7.0.0-rc.2.22472.3 \
+    # SDK version
+    DOTNET_SDK_VERSION=7.0.100-rc.2.22477.23 \
+    # Enable correct mode for dotnet watch (only mode supported in a container)
+    DOTNET_USE_POLLING_FILE_WATCHER=true \
+    # Skip extraction of XML docs - generally not useful within an image/container - helps performance
+    NUGET_XMLDOC_MODE=skip    
 
-# [Optional] Uncomment this line to install global node packages.
-# RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1
+ARG TARGET_JAVA_VERSION=17
+ARG JAVA_HOME=/usr/lib/jvm/msopenjdk-${TARGET_JAVA_VERSION}
+
+# Java Environment variables
+ENV \
+    # Default to UTF-8 file.encoding
+    LANG en_US.UTF-8 \
+    JAVA_HOME ${JAVA_HOME} \
+    SDKMAN_DIR="/usr/local/sdkman" \
+    PATH="${JAVA_HOME}/bin:${SDKMAN_DIR}/candidates/java/current/bin:${PATH}"
+
+
+RUN \
+    # Install .NET Runtime
+    curl -fSL --output dotnet.tar.gz https://dotnetcli.azureedge.net/dotnet/Runtime/$DOTNET_VERSION/dotnet-runtime-$DOTNET_VERSION-linux-x64.tar.gz \
+    && dotnet_sha512='2294605e371ec575e59baa1eacf973d7dd6761d5d161f4988ed6c51d5db2795a4dc95709d6eaf38ddb2caee6f0551225b49be5cbe42233c2ffae3a0f63d4412c' \
+    && echo "$dotnet_sha512  dotnet.tar.gz" | sha512sum -c - \
+    && mkdir -p /usr/share/dotnet \
+    && tar -oxzf dotnet.tar.gz -C /usr/share/dotnet \
+    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet \
+    && rm dotnet.tar.gz \
+    # Install .NET SDK
+    && curl -fSL --output dotnet.tar.gz https://dotnetcli.azureedge.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-sdk-$DOTNET_SDK_VERSION-linux-x64.tar.gz \
+    && dotnet_sha512='22db5d1d16f6fcedfc46f87896920425b5d9b61d09c47d254d6ac731c6d853657882b21faf21f313ed20b33e6331d01b9f723b2c586f0e0cf5acc5ed570b0260' \
+    && echo "$dotnet_sha512  dotnet.tar.gz" | sha512sum -c - \
+    && mkdir -p /usr/share/dotnet \
+    && tar -oxzf dotnet.tar.gz -C /usr/share/dotnet ./packs ./sdk ./sdk-manifests ./templates ./LICENSE.txt ./ThirdPartyNotices.txt \
+    && rm dotnet.tar.gz \
+    # Trigger first run experience by running arbitrary cmd
+    && dotnet help \
+
+    # Install Microsoft OpenJDK
+    && arch="$(dpkg --print-architecture)" \
+	&& case "$arch" in \
+		"amd64") \
+			jdkUrl="https://aka.ms/download-jdk/microsoft-jdk-${TARGET_JAVA_VERSION}-linux-x64.tar.gz"; \
+			;; \
+		"arm64") \
+			jdkUrl="https://aka.ms/download-jdk/microsoft-jdk-${TARGET_JAVA_VERSION}-linux-aarch64.tar.gz"; \
+			;; \
+		*) echo >&2 "error: unsupported architecture: '$arch'"; exit 1 ;; \
+	esac \
+	\
+	&& wget --progress=dot:giga -O msopenjdk.tar.gz "${jdkUrl}" \
+	&& wget --progress=dot:giga -O sha256sum.txt "${jdkUrl}.sha256sum.txt" \
+	\
+	&& sha256sumText=$(cat sha256sum.txt) \
+	&& sha256=$(expr substr "${sha256sumText}" 1 64) \
+	&& echo "${sha256} msopenjdk.tar.gz" | sha256sum --strict --check - \
+	&& rm sha256sum.txt* \
+	\
+	&& mkdir -p ${JAVA_HOME} \
+	&& tar --extract \
+		--file msopenjdk.tar.gz \
+		--directory ${JAVA_HOME} \
+		--strip-components 1 \
+		--no-same-owner \
+	&& rm msopenjdk.tar.gz* \
+	\
+	&& ln -s ${JAVA_HOME} /docker-java-home \
+	&& ln -s ${JAVA_HOME} /usr/local/openjdk-${TARGET_JAVA_VERSION}
+
+# Copy library scripts to execute
+COPY library-scripts/*.sh library-scripts/*.env /tmp/library-scripts/
+
+# [Option] Install zsh
+ARG INSTALL_ZSH="true"
+# [Option] Upgrade OS packages to their latest versions
+ARG UPGRADE_PACKAGES="true"
+# Install needed packages and setup non-root user. Use a separate RUN statement to add your own dependencies.
+ARG USERNAME=vscode
+ARG USER_UID=1000
+ARG USER_GID=$USER_UID
+RUN bash /tmp/library-scripts/common-debian.sh "${INSTALL_ZSH}" "${USERNAME}" "${USER_UID}" "${USER_GID}" "${UPGRADE_PACKAGES}" "true" "true" \
+    && bash /tmp/library-scripts/java-debian.sh "none" "${SDKMAN_DIR}" "${USERNAME}" "true" \
+	&& apt-get clean -y && rm -rf /var/lib/apt/lists/*
+    # Remove library scripts for final image
+RUN rm -rf /tmp/library-scripts
